SHELL := bash
MAKEFLAGS += --warn-undefined-variables
.SHELLFLAGS := -euo pipefail -c
.DEFAULT_GOAL := provision

THIS_MAKEFILE := $(abspath $(firstword $(MAKEFILE_LIST)))
THIS_MAKEFILE := `python3 -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' ${THIS_MAKEFILE}`
SRC_ROOT := $(shell dirname ${THIS_MAKEFILE})

docs:
	@# Rewrite the main README from README.md.j2,
	@# inserting the current results of `--help`
	autogenerated_help="`graven --help`" \
	j2 -f env README.md.j2 \
	| tee ${SRC_ROOT}/README.md
